package kr.nanoit.config;

/**
 * The type Index login ack.
 */
public class IndexLoginAck {
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_RESULT_CODE.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_RESULT_CODE = IndexHeader.COMMON_INDEX_HEADER_FULL_LENGTH;
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_SMS_TPS.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_SMS_TPS = COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_RESULT_CODE + LengthLoginAck.COMMON_LENGTH_LOGIN_ACKNOWLEDGEMENT_RESULT_CODE;
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_LMS_TPS.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_LMS_TPS = COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_SMS_TPS + LengthLoginAck.COMMON_LENGTH_LOGIN_ACKNOWLEDGEMENT_SMS_TPS;
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_MMS_TPS.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_MMS_TPS = COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_LMS_TPS + LengthLoginAck.COMMON_LENGTH_LOGIN_ACKNOWLEDGEMENT_LMS_TPS;
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_KAT_TPS.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_KAT_TPS = COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_MMS_TPS + LengthLoginAck.COMMON_LENGTH_LOGIN_ACKNOWLEDGEMENT_MMS_TPS;
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_KFT_TPS.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_KFT_TPS = COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_KAT_TPS + LengthLoginAck.COMMON_LENGTH_LOGIN_ACKNOWLEDGEMENT_KAT_TPS;
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_GMS_TPS.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_GMS_TPS = COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_KFT_TPS + LengthLoginAck.COMMON_LENGTH_LOGIN_ACKNOWLEDGEMENT_KFT_TPS;
    /**
     * The constant COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_FULL.
     */
    public static int COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_FULL = COMMON_INDEX_LOGIN_ACKNOWLEDGEMENT_GMS_TPS + LengthLoginAck.COMMON_LENGTH_LOGIN_ACKNOWLEDGEMENT_GMS_TPS;
}